name: doctor_pet
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  collection: ^1.18.0
  dartz: ^0.10.1
  equatable: ^2.0.5
  fl_chart: ^0.67.0
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_localizations:
    sdk: flutter
  flutter_polyline_points: ^2.0.0
  geolocator: ^11.0.0
  get: ^4.6.5
  google_maps_flutter: ^2.6.0
  http: ^1.2.1
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  responsive_framework: ^1.4.0
  shared_preferences: ^2.2.2
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
  - assets/
  - assets/img/
  - assets/image/
